language: php
php:
- 7.0
matrix:
  allow_failures:
  - php: hhvm
cache:
  directories:
  - "$HOME/.composer/cache"
git:
  depth: 1
addons:
  mariadb: '10.1'
  firefox: 47.0.1
  hosts:
  - xepan-local.org
  - demo.xepan-local.org
before_install:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
- cp -r tests ~/tests
- rm -rf *
- rm -rf .git
- git clone --depth=1 --branch=develop https://github.com/xepan/xepan2.git
- mv xepan2/* .
- echo "Extracting firefox and setting PATH variable..."
- tar -xjf /tmp/firefox-47.0.1.tar.bz2 --directory /tmp
- export PATH="/tmp/firefox:$PATH"
- echo "Using firefox version `firefox --version`"
- sudo curl -LsS http://codeception.com/codecept.phar -o /usr/local/bin/codecept
- sudo chmod a+x /usr/local/bin/codecept
- sudo apt-get update
- sudo apt-get install apache2 libapache2-mod-fastcgi
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv
  version-name)/etc/php-fpm.conf
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default
  ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
- sudo chown -R travis:travis /var/lib/apache2/fastcgi
- "~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm"
- sudo cp -f tests/travis/build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
- sudo service apache2 restart
- wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
- wget -P ~/Downloads https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz
- tar -xf ~/Downloads/geckodriver-v0.10.0-linux64.tar.gz -C ~/Downloads
- composer self-update
- composer install --prefer-source --no-dev
- ulimit -c unlimited || true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- java -jar selenium-server-standalone-2.53.1.jar -port 4444 > /dev/null &
- sleep 5
- mysql -e 'create database testdb;'
- cp -r ~/tests .
- codecept build
script:
- codecept run acceptance --env travis --html index.html
- bash ./tests/deploy-to-gh-pages.sh
env:
  global:
  - GITHUB_REPO: xavoctechnocratspvtltd/_xepan2
  - REPORT_FOLDER: marketing
  - secure: jWPqPXQG9wIvHHfhF6ZT/QEnhNE9kZklD0UUzbt1o3EqJ5co21wvfujIzY5gXLNydnlLRPZjxP+i6nfqrSQonU6LfSt6PKtXBWI4KzYkeq2Bf0hMCRXx68LrW6IORKyJVh9+WoE84+Tx/qXv/apt7HT3eOqDCcFwhU2ZaP/E1WnnT6v80wm6b5GAUQR+/oH5C8wrnKn3aga/YRoefNqW/J9ZMExxUu0SULKW18DUEBnzgdqx5kyJPdq1YFZpHdsnlAehfsDAZF9fkS0OtVqznQpfhbqhSn8532lkw2is+prmBwA/Bdi9rFA5ZHWGGdaS/IEq3DYY6xYuh6Rh10uKfbesoN2jrNPmXewhbgYIKvPAgwPaYCGq00h4BvYhJN4EaYqUvgEBSdTm98Fbk38usM5drgLcA0XYZRp+dmUnWw50QQWtj1VbXzRz3+pEjUK+LvDK/hOjl36zhP7eYw0pdRjIwoOLAt1Oq/HDmmjccv1vOIdTqaDsu9VOF3mSLyqtCq3fzbzk4h1iJdMmK7ifXGKf5nbXe7U3VQ8EFzH91UWPAKF9OIb60rOdJdheRzBT9L9h8jJ+EaT0+J+svJrxNLJRxmVsZw2td8/Zij6qx6R9Y+HMT1PIxx5magqAL2rEAJGaqAh8Qct33FmUE62ypJq1HwoJbih7G0ZZSNzDpTo=
